name: learn-github-actions
on: push
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
