name: learn-github-actions
on: push
jobs: 
  Explore-Github-Actions: 
    runs-on: ubuntu-latest
    steps:
      - name: Add env variables to liana proj
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event. secret is ${{ secrets.GOOGLE_MAPS_API_KEY }}"
